### ISSUE TITLE
大佬！可以出个中文版本吗

### ISSUE THREAD

**Issue by tuanzi11** [Bidziilla/ACNH-ToolKit#1]
谢谢啦大佬  请求弄个中文版！

**Comment by Bidziilla** [comment]
感谢您的客气话。 我目前没有中文版本的计划，因为我只会说英语。

**Comment by tuanzi11** [comment]
以后有机会开源吗？ 大佬！ 🥹🥹🥹

**Comment by Bidziilla** [comment]
> 以后有机会开源吗？ 大佬！ 🥹🥹🥹

目前没有计划发布源代码。这个工具包只是对未来的一个尝试。敬请关注。
