### ISSUE TITLE
Here are some of my Sinicization, I hope it can help you, please correct me if there are any deficiencies.

### ISSUE THREAD

**Issue by q1378659137** [Bidziilla/ACNH-ToolKit#2]
![Uploading Screenshot 2023-03-23 02-40-34_1.png…]()
物品百宝箱
速度与激情
蒙蔽你的双眼
杂七杂八
法律信息
-----------------------
能吃所有东西
无限制的扔所有东西

第一行第一列物品ID

修改物品ID个位数
修改物品ID十位数
修改物品ID百位数
修改物品ID千位数
把这个选项写入游戏
-----------------------
穿墙
急急急！我要起飞的速度
没想到小动物比我还急
-----------------------
进入自由色相头
火鸡想要北京早上的天气
今天的风儿甚是喧嚣
火鸡想变大
火鸡也想让动物变大
让我们一起摇摆
------------------------
移动色相头
改变焦距
色相头垂直上下移动
色相头倾斜上下角度
色相头左右倾斜
扁平化这个世界
传送到当前镜头中心位置
清除当前所有设置，累觉不爱

敲黑板划重点：
如果色相头倾斜不起作用
那么就按下A键清除当前所有设置
-----------------------------
改变粒子特效(走路放屁)
火鸡想要浪漫的花瓣
河里花瓣知多少
想试试飘树叶吗
脸红心跳的感觉

解锁滤镜
-----------------------------
红
绿
蓝
核心颜色1
核心颜色2
光线强度
switch亮度
------------------------------
禁用此软件中所有设置

你看我跑的快不快
商店一直开门(周扒皮都要叫你老师)
改变时间
闭嘴！BGM
查看色相头信息
-------------------------------

警告：
该软件不得售卖！ 如果您为该软件付费了，不管怎样
，您都被骗了，应该要求退款！

注意：我（Bidzilla）不会对您存档的任何损
坏负责，包括您的switch被ban。通过使用这个
Tesla插件。你必须同意这个。你对你的行为负责。

另外：
我 (Bidziilla) 不容忍以现实世界的现金出售游戏内物品。
这他妈的很糟糕如果你这样做了，你就是个混蛋。

♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥

感谢这些人：
Shesez, Wilbo.SkyQueen. Tristan.Lukas. Delstrax.and Slattz.
你们太棒了！

**Comment by Bidziilla** [comment]
目前没有中文翻译的计划。 对于给您带来的任何不便，我深表歉意。
我不认为特斯拉完全支持中文字符集。 然而，我可能大错特错。
测试菜单的翻译版本会导致滚动错误。 我可以解决这个问题，但我还有其他事情需要解决。

![IMG_20230322_162451](https://user-images.githubusercontent.com/93905489/227029852-86135611-ff14-4c27-a552-04b15a80f094.jpg)

**Comment by q1378659137** [comment]
十分感谢您的付出，特斯拉是可以支持中文的，您先忙您的事情，期待您插件的中文化。我是从群内得知您的插件，您的插件很棒，并且我会向朋友介绍您的插件。

**Comment by Bidziilla** [comment]
> 十分感谢您的付出，特斯拉是可以支持中文的，您先忙您的事情，期待您插件的中文化。我是从群内得知您的插件，您的插件很棒，并且我会向朋友介绍您的插件。

一个小组？ 在哪里？ 我想看看，因为我绝对可以提供支持和解释。中文翻译是可以的。 但是，不会很快到来。（我用谷歌翻译。）

**Comment by q1378659137** [comment]
![QQ截图20230325152105](https://user-images.githubusercontent.com/35685331/227703275-cc5923dc-eb59-43bc-a113-e8793adc9ac4.png)
这是我的QQ群，您上个关闭的汉化问题，发起者就是在我的QQ群内提及的，我的QQ群是600622975，如果您需要文字翻译我们也可以帮助您，我翻译的相对来说没有那么官方，这里是QQ聊天软件官网：im.qq.com，感谢您的汉化

**Comment by Bidziilla** [comment]
我明白。 我有一个旧的 Discord 服务器，如果人们有任何问题可以联系我。 有一个非英语频道，他们可能会在那里讲话。 作弊请求不会被接受，因为我有足够的作弊来提供未来的项目版本。
如果我简化叠加层中的文本，是否会提高说中文的人的可读性？

https://discord.gg/ZYngpJ9TmK

**Comment by q1378659137** [comment]
好的，我已接收邀请，谷歌汉化属于机翻，部分语句不通顺，如果您需要简化，我会给您提供一个简易版本的方案

**Comment by tuanzi11** [comment]
冲

**Comment by Bidziilla** [comment]
Chinese translation implemented in version 1.6.
