### ISSUE TITLE
[Enhancement] Show Indicator when options are running

### ISSUE THREAD

**Issue by DraconicNEO** [Bidziilla/ACNH-ToolKit#3]
I think it would be a good idea to show when toggles are active in the menu so that you know which ones you're using since the current way it is you kind of have to enable them blindly.

**Comment by Bidziilla** [comment]
In the latest development build, I've added a feature that could give a few cheats a little reminder that they're active. The catch is, only one reminder can show up at a time. (The text gets displayed in-game, not in ToolKit.)
It's a cool idea, but would be a memory hog to complete it entirely for this project. If we hardcoded the menu to show which cheats are on or off, it'd mean a bunch of rework for each entry in the menu would need to be done, and we'd probably end up using more memory than we want to, resulting in less room for new cheats. I'll keep you posted on any progress with the reminder part if I ever decide to use it in ToolKit. Also, sorry it took me nearly a year to reply.
