### ISSUE TITLE
how to use this with emulator?

### ISSUE THREAD

**Issue by Kenfin7** [Bidziilla/ACNH-ToolKit#4]
I'm using yuzu, and would like to know how to use it on there

**Comment by Snakes13x** [comment]
Short answer is that it is not going to work. It requires 2 pieces of software to run on switch and Yuzu does not support either.

**Comment by Bidziilla** [comment]
As Snakes said, this will never be supported in an emulator, it requires Tesla and nxovlloader to run. I do not know if it's possible to make this work in an emulator, and I do not have any interest in trying to figure it out.
